export const thesAboutTexts = {
    'EuroVoc': 'The EU Vocabularies website provides access to vocabularies managed by the EU institutions and bodies. This includes controlled vocabularies, schemas, ontologies, data models, etc. As part of the EU open data initiative, the EU Vocabularies website offers free public access to all of its content. The assets, information and documentation in this site are meant for a wide range of interests and user profiles. The occasional user can find metadata from a large number of controlled vocabularies. Specialised users, such as indexers, can access the multilingual thesaurus EuroVoc. Frequent and tech-savvy users will surely appreciate multiple formats available for download, alignments with other controlled vocabularies, versioning information and descriptive and release-related documentation. All types of users can choose to create their profile for a personalised interaction with the website. The EU Vocabularies website replaces the EuroVoc and the Metadata Registry (MDR) sites and is managed by the Publications Office of the EU.',

    'STW': 'The STW Thesaurus for Economics is the world\'s most comprehensive bilingual thesaurus for representing and searching for economics-related content. With its almost 6,000 subject headings in English and German and more than 20,000 synonyms it covers all economics-related subject areas and, on a broader level, the most important related subject fields. The STW is published and continuously further developed by the ZBW according to the latest changes in the economic terminology. As a generally re-usable concept system it is used by universities, research institutes, public institutions and companies for knowledge organization and for research and development in computer and information science as well as in the area of Linked Data and Semantic Web technologies. It has been published as one of the first thesauri in the Linked Open Data Cloud and is linked to other vocabularies through mappings. The STW is part of cross-linked information environments and web services for processing and linking economic literature, research data, author profiles and educational material.',

    'Gemet': 'GEMET, the GEneral Multilingual Environmental Thesaurus, has been developed as an indexing, retrieval and control tool for the European Topic Centre on Catalogue of Data Sources (ETC/CDS) and the European Environment Agency (EEA), Copenhagen. The work has been carried out through a contract between the EEA and the ETC/CDS which is led by the Ministry of the Environment of Lower Saxony, includes members of Germany, Austria, Italy, Sweden and benefits of the collaboration of other member countries of the European Union (EU), as well as of UNEP Infoterra.\n' +
        '\n' +
        'The basic idea for the development of GEMET was to use the best of the presently available excellent multilingual thesauri, in order to save time, energy and funds. GEMET was conceived as a “general” thesaurus, aimed to define a common general language, a core of general terminology for the environment. Specific thesauri and descriptor systems (e.g. on Nature Conservation, on Wastes, on Energy, etc.) have been excluded from the first step of development of the thesaurus and have been taken into account only for their structure and upper level terminology.',

    'Unescothes': 'The UNESCO Thesaurus is a controlled and structured list of concepts used in subject analysis and retrieval of documents and publications in the fields of education, culture, natural sciences, social and human sciences, communication and information. Continuously enriched and updated, its multidisciplinary terminology reflects the evolution of UNESCO\'s programmes and activities.\n' +
        '\n' +
        'The first edition of the Thesaurus was released in English in 1977, with French and Spanish translations in 1983 and 1984. The second revised and restructured version was released in 1995. Today the Thesaurus is available in English, French, Russian and Spanish.\n' +
        '\n' +
        'Concepts are grouped into 7 broad subject areas which are broken down into microthesauri. The UNESCO Thesaurus is compliant with the ISO 25964 standard. For more information on the structure of the thesaurus and its historical background please consult the thesaurus introduction.\n' +
        '\n' +
        'The UNESCO Thesaurus is mainly used for indexing and searching resources in UNESCO’s document repository.',

    'AgroVoc': 'The AGROVOC thesaurus was first published (in English, Spanish and French) at the beginning of the 1980s by the Food and Agriculture Organization (FAO) of the United Nations. In 2000, AGROVOC abandoned paper printing and went digital, with data storage handled by a relational database. In 2009 AGROVOC became an SKOS resource.\n' +
        '\n' +
        'Today, AGROVOC is available  as an SKOS-XL concept scheme, also published as a Linked Data (LD) set composed of 36,000+ concepts available in up to 33 languages. By means of LD, AGROVOC is aligned to 18 open datasets related to agriculture (see: AGROVOC LD). The advantage of having a thesaurus like AGROVOC published as LD is that once thesauri are linked, the resources they index are linked as well.\n' +
        '\n' +
        'AGROVOC is widely used in specialized libraries as well as digital libraries and repositories to index content and for the purpose of text mining. It is also used as a specialized tagging resource for knowledge and content organization by FAO and other third-party stakeholders.\n' +
        '\n' +
        'Currently, AGROVOC multilingual thesaurus is a collaborative effort, coordinated by FAO, and maintained by an international community of experts and institutions active in the area of agriculture and related domains. For more information on the AGROVOC community see People. If you or your institution would like to contribute to a particular language or translate AGROVOC into a new language, please contact us at agrovoc@fao.org',
};
